### ISSUE TITLE
Not working again, just pauses at the end of a short

### ISSUE THREAD

**Issue by inkayfan** [Tyson3101/Auto-Youtube-Shorts-Scroller#13]
I F12'd it and im getting tons of these errors:
Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)

**Comment by Tyson3101** [comment]
Hi thanks for that info, can you check if you need to update
![image](https://user-images.githubusercontent.com/67045138/229268333-5e48f5fc-5397-411c-bdb2-e5d4acad96e4.png)

**Comment by Tyson3101** [comment]
Nvmm, I have just magically got this too lol. and will fix it asap. Sorry bit of a silly error on my part

**Comment by Tyson3101** [comment]
Hi, The extension has been updated and looks all good on my end.
If face any other issues check if updated to v 2.2.2

**Comment by inkayfan** [comment]
Thanks big man
