### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by patjapat** [Tyson3101/Auto-Youtube-Shorts-Scroller#15]
After last update problems began. Today it stopped working completely for me. I've got 2.2.1 Tried reinstalling, rebooting, everything. See some console errors here:

desktop_polymer.js:4031 LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
googleads.g.doubleclick.net/pagead/id:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ad_status.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
26The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
533content.js:146 Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)
checkIfVaildVideo @ content.js:146
checkForNewShort @ content.js:64
setInterval (async)
initiate @ content.js:185
(anonymous) @ content.js:243
VM28:201          GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT
theSend @ VM28:201
$pa @ desktop_polymer.js:1417
Yi @ desktop_polymer.js:1404
(anonymous) @ desktop_polymer.js:10772
jh @ desktop_polymer.js:926
QFb @ desktop_polymer.js:10769
(anonymous) @ desktop_polymer.js:10789
(anonymous) @ desktop_polymer.js:1363
241content.js:146 Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)
checkIfVaildVideo @ content.js:146
checkForNewShort @ content.js:64
setInterval (async)
initiate @ content.js:185
(anonymous) @ content.js:243
726content.js:146 Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)
checkIfVaildVideo @ content.js:146
checkForNewShort @ content.js:64
VM28:201          GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT
theSend @ VM28:201
$pa @ desktop_polymer.js:1417
Yi @ desktop_polymer.js:1404
(anonymous) @ desktop_polymer.js:10772
jh @ desktop_polymer.js:926
QFb @ desktop_polymer.js:10769
(anonymous) @ desktop_polymer.js:10789
(anonymous) @ desktop_polymer.js:1363
98content.js:146 Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)
checkIfVaildVideo @ content.js:146
checkForNewShort @ content.js:64

**Comment by Tyson3101** [comment]
Yo thanks for the heads up and help with the error message, I have fixed that error (might have been an easily avoidable one, sorry) and all looks good now. So it should be fixed once google reviews the update (take a day or two).

**Comment by Tyson3101** [comment]
Hi, The extension has been updated and looks all good on my end.
If face any other issues check if updated to v 2.2.2

**Comment by patjapat** [comment]
yes, it works now. Thanks a lot!
