### ISSUE TITLE
IDK how to update please help!

### ISSUE THREAD

**Issue by Patrik456** [Tyson3101/Auto-Youtube-Shorts-Scroller#16]

**Comment by Patrik456** [comment]
btw im on opera gx browser

**Comment by Tyson3101** [comment]
Hi, the extension is broken atm, but in a day or two, once google reviews the update, it should be fixed.
And I believe the extension should be updated automatically.

**Comment by Tyson3101** [comment]
Yeah it should, if you have any issues just msg me here

**Comment by Patrik456** [comment]
ok thanks

**Comment by Tyson3101** [comment]
Hi, The extension has been updated and looks all good on my end.
If you face any other issues check if it has updated on its own to v 2.2.2
