### ISSUE TITLE
Auto Scroll Broken Again Chrome Extension

### ISSUE THREAD

**Issue by Seathre** [Tyson3101/Auto-Youtube-Shorts-Scroller#18]
`Uncaught TypeError: filterMinLikes.replaceAll is not a function
    at checkIfVaildVideo (content.js:190:41)
    at checkForNewShort (content.js:73:14)
checkIfVaildVideo	@	content.js:190
checkForNewShort	@	content.js:73`

Only console errors related to the extension I could find. Hope it helps.

**Comment by Tyson3101** [comment]
Hi thanks for this and sorry. The reasoning for that is I changed the filter works. 
_### **For you, a fix should be to (re)set a value for the filter, then either remove it or keep it**_, so it will make it the correct value where that function will work.
But thanks for telling me about this so I can automatically set this and stop from other people experiencing this

**Comment by Tyson3101** [comment]
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/67045138/62e5a35e-557d-411b-884f-cb776344792d)

**Comment by Seathre** [comment]
Sorry for the late reply. That was in fact the problem, thank you.
