### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Seathre** [Tyson3101/Auto-Youtube-Shorts-Scroller#19]
We can blacklist specific channels, but I would like to whitelist specific channels to bypass the filters. This could be a text box containing channel names, like your block feature. Alternatively, whitelisting all subscribed channels would be a big time saver, though I would still like the blacklist to take priority, in case I need to block shorts from a creator whose long-form content I still enjoy.

**Comment by Tyson3101** [comment]
Hi sorry for missing this issue.
I am not really sure what you mean by this. Are you saying **only** show shorts from the whitelisted channels?
