### ISSUE TITLE
Creator Blacklist not skipping creator

### ISSUE THREAD

**Issue by Faloof** [Tyson3101/Auto-Youtube-Shorts-Scroller#20]
So I'm attempting to blacklist certain creators that I see alot, but don't really care about, when I input the creators name It just doesnt do anything

**Comment by Tyson3101** [comment]
Hey, I just tested it out and seems to work alright for me, can you send a screenshot of what you are inputting?
A possible case could be you have a space after the comma (Which is something I should allow in future)

**Comment by Faloof** [comment]
No space after comma 
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/96490994/e5b6790c-87cb-4cfd-9114-b5e40cfd2489)

**Comment by Tyson3101** [comment]
Hi sorry I **totally** forgot about this gh issue, I still can't replicate the issue.
Are you still facing this issue? And if you are do you see any errors or other information that could be helpful?

**Comment by Faloof** [comment]
Found out, it was just my version being weird and not wanting to update, it works now!

**Comment by Tyson3101** [comment]
Ok nice glad to hear
