### ISSUE TITLE
filter by title/hashtags

### ISSUE THREAD

**Issue by formidablyclueless** [Tyson3101/Auto-Youtube-Shorts-Scroller#24]
It'd be nice to be able to filter out certain content that usually has a certain tag or title element, such as certain topics.

For example, imagine filtering out every short with #familyguy or something like that, instead of blacklisting every creator, where you would forget who any of them are if you went back on your decision.
It'd also be pretty funny to see what kind of content there would be if you filtered out everything with #fyp in it

**Comment by Tyson3101** [comment]
Yeah this a feature I will definitely add at some point soon, I be getting random league of legend shorts so I need it myself lol

**Comment by Tyson3101** [comment]
I've just published an update to the extension with tag filtering
