### ISSUE TITLE
Auto scroller stop working.

### ISSUE THREAD

**Issue by Tarlok-TC** [Tyson3101/Auto-Youtube-Shorts-Scroller#28]
It was working perfectly but now suddenly it stops working after 10 YT shorts. It is happing in all browsers. What is the issue? Please help.

**Comment by Tyson3101** [comment]
Hey, I have just tested and don't face this issue, are you still experiencing this? 
If you are, can you provide more info on how it stops working, like do you see any errors in the console, etc.

Sorry for the late reply and thanks

**Comment by Tarlok-TC** [comment]
@Tyson3101 Thank you for the updates. I have checked again and now it is working fine. I don't know why it was stopped just few days ago. It is working fine, and I will let you know if face any issue in near future. Also, thanks for making such a useful tool.

**Comment by Tyson3101** [comment]
Ah nice, and no problem glad you enjoy the extension.
