### ISSUE TITLE
Not autoscrolling

### ISSUE THREAD

**Issue by aznkree** [Tyson3101/Auto-Youtube-Shorts-Scroller#29]
Extension isn't autoscrolling. In the console it shows:

1. Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute refers to a form field by its name, not its id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, refer to form fields by their id attribute.
1 resource

3. Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
3 resources

1. Page layout may be unexpected due to Quirks Mode
One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.
Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.

**Comment by ahmadalashtar** [comment]
I'm going to try to write my own extension, something that'd get the job done, nothing fancy.

**Comment by Tyson3101** [comment]
Hi, Sorry I have just published a new version with small updates to try and fix it not auto-scrolling,
Please let me know if it has any had success and sorry for the long wait in responses.

**Comment by ahmadalashtar** [comment]
> Hi, Sorry I have just published a new version with small updates to try and fix it not auto-scrolling, Please let me know if it has any had success and sorry for the long wait in responses.

No luck, doesn't work for me

**Comment by aznkree** [comment]
Still not working, tried installing and reinstalling

**Comment by Tyson3101** [comment]
Do you both have this version of the extension? ([https://chromewebstore.google.com/detail/ckbnikemebopgknkpgjlkbffpkkhblbe](https://chromewebstore.google.com/detail/ckbnikemebopgknkpgjlkbffpkkhblbe)),
As a older version of mine is no longer on the web store.

**Comment by ahmadalashtar** [comment]
I tried today, it works for me.

**Comment by aznkree** [comment]
Working for me now! Thanks

**Comment by Tyson3101** [comment]
Ay glad to hear, I didn't change anything so maybe was just a youtube issue. 
Sorry for not being much help been busy and wasn't sure what the issue could be due to working for me.
And of course if do face any other issues let me know!
