### ISSUE TITLE
Doesn't scroll all the way anymore.

### ISSUE THREAD

**Issue by RoyvanEmpel** [Tyson3101/Auto-Youtube-Shorts-Scroller#36]
Hello,

Both me and a friend have noticed that the plugin no longer scrolls all the way down to the next video. Resizing the window / going into fullscreen mode / scrolling yourself / pausing the video "fixes" the problem for a single time, it will break again on the next autoscroll.

We are both using the Brave browser and havn't yet tried if this issue also exists on a different browser.\
My brave version: Version 1.67.119 Chromium: 126.0.6478.114

I'm using Linux, and he is using Windows 11.
Both on 1440p monitors.

Here are a few screenshots in from the entire height of the screen. You can see that for some reason the bottom of the video is not visible and the in the top it is showing the last video.

![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/47390057/4e4f6445-5964-4c07-aac8-ab9904301d60)
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/47390057/a8930f7c-331e-41c6-b511-a3727a6521eb)
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/47390057/afc7c580-223a-4afc-a0ea-50d391518830)

If i can provide some more info that please let me know :).

**Comment by RoyvanEmpel** [comment]
Someone seems to have made a pull request about this issue.
https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/pull/35

**Comment by Tyson3101** [comment]
Hi thanks for this issue,
I have merged the pull request and have just updated the extension.
I haven't been able to replicate the scrolling issue myself so if you can let me know if it has fixed it and/or you face any other issues.
Thanks again

**Comment by carscx** [comment]
Same issue here, in Edge Chrome, Windows 11, resolution 4k (3840x1920)

![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/7082868/6f80a845-6786-4baf-83d4-a13850758d5b)

**Comment by Tyson3101** [comment]
Still experience it on v2.5.3?
https://chromewebstore.google.com/detail/auto-youtube-shorts-scrol/ckbnikemebopgknkpgjlkbffpkkhblbe

**Comment by RoyvanEmpel** [comment]
After removing completely removing version 2.5.1 and installing 2.5.3 it seems to now scroll again like before.

A ctrl + f5 was required to get it to work.

**Comment by Tyson3101** [comment]
Nice, glad to hear

Thanks again for this issue
