### ISSUE TITLE
Instagram reels individual accounts scroll

### ISSUE THREAD

**Issue by UIWHd** [Tyson3101/Auto-Youtube-Shorts-Scroller#37]
Hi, what if you add a feature where you can auto-scroll on individual accounts on Instagram reels? label:enhancement

https://github.com/user-attachments/assets/eb9a22ff-42b6-4e41-9e70-0118e7683fc4

**Comment by Tyson3101** [comment]
Hey really sorry for missing this,
That is definitely a good feature to add for the reels scroller, and I will look into adding that when ever I have time.
