### ISSUE TITLE
inconsistant

### ISSUE THREAD

**Issue by freak-coding** [Tyson3101/Auto-Youtube-Shorts-Scroller#5]
It sometimes works and sometimes doesnt. It seems after I manually go to next short it stop working. Am I doing something wrong??

**Comment by Tyson3101** [comment]
That is definitely not meant to happen, 
can I ask what page/URL of shorts are you on? 

And if you could, is it possible for you to screen-record it? Because I am unable to recreate this issue.

**Comment by freak-coding** [comment]
I seem to have fixed it by uninstalling and reinstalling. Works flawlessly now. Thankyou for the help!!!

**Comment by Tyson3101** [comment]
W
