### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by zmikolaj** [Tyson3101/Auto-Youtube-Shorts-Scroller#6]
make it that it not auto scroll when you checking comments

**Comment by Tyson3101** [comment]
Hi, the extension does have this feature
<img width="326" alt="ScrollOnComments" src="https://user-images.githubusercontent.com/67045138/210287558-142e1f28-e057-45df-8490-fae2e3fb9b45.png">
Do you have this unticked? If you do and it doesn't seem to work for you, I can try to look for a reason why
